root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/api-public"
  cmd = "swag init -g cmd/api-public/main.go -o cmd/api-public/docs --exclude cmd/api-ingester && swag fmt -d ./cmd/api-public && go build -o ./tmp/api-public ./cmd/api-public"
  delay = 50
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go", "docs.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = 50
  log = "build-errors.log"
  poll = false
  poll_interval = 50

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
